#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <sys/types.h>
#include <limits.h>
#include "unlink_monitor.skel.h" // Generated by bpftool or libbpf
#include "unlink_monitor.h"

#define CWD_PATH_LEN 4096

static int handle_event(void *ctx, void *data, size_t data_sz) {
    const struct event *e = data;
    char proc_cwd_path[PATH_MAX];
    char cwd[CWD_PATH_LEN];
    char full_path[PATH_MAX + FILENAME_MAX];

    snprintf(proc_cwd_path, sizeof(proc_cwd_path), "/proc/%d/cwd", e->pid);
    ssize_t len = readlink(proc_cwd_path, cwd, sizeof(cwd) - 1);
    if (len < 0) {
        perror("readlink");
        return 0;
    }

    cwd[len] = '\0';
    snprintf(full_path, sizeof(full_path), "%s/%s", cwd, e->filename);

    printf("PID %d deleted file: %s\n", e->pid, full_path);
    return 0;
}

int main(void) {
    struct unlink_monitor_bpf *skel;
    int err;

    // Open and load the BPF program
    skel = unlink_monitor_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "Failed to open and load BPF skeleton\n");
        return 1;
    }

    // Attach kprobe
    err = unlink_monitor_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach BPF program\n");
        goto cleanup;
    }

    // Set up ringbuf
    struct ring_buffer *rb = ring_buffer__new(bpf_map__fd(skel->maps.events), handle_event, NULL, NULL);
    if (!rb) {
        fprintf(stderr, "Failed to create ring buffer\n");
        goto cleanup;
    }

    printf("Listening for unlink events...\n");

    // Poll events
    while (1) {
        err = ring_buffer__poll(rb, 100 /* ms */);
        if (err < 0) {
            fprintf(stderr, "Error polling ring buffer: %d\n", err);
            break;
        }
    }

cleanup:
    unlink_monitor_bpf__destroy(skel);
    return err != 0;
}

